version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: accident_severity_back
    ports:
      - "8000:8000"
    volumes:
      - ./back/data:/app/data   # dossier partagé entre hôte et conteneur
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: accident_severity_front
    ports:
      - "8050:8050"
    depends_on:
      - back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge