
services:
  db:
    image: postgres:13
    container_name: accident_severity_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accidents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d accidents"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  back:
    #build:
     # context: ./back
      #dockerfile: Dockerfile
    container_name: accident_severity_back
    image: inesmarouani/accident-back:latest
    ports:
      - "8000:8000"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: accidents
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./back/data:/code/app   # dossier partagé entre hôte et conteneur
      - ./back/models_trained:/code/models_trained
      # Volume pour uv cache (optionnel, améliore les rebuild)
      - uv-cache:/root/.cache/uv    
    networks:
      - app-network

  front:
    #build:
     # context: ./front
      #dockerfile: Dockerfile
    container_name: accident_severity_front
    image: inesmarouani/accident-front:latest
    ports:
      - "8050:8050"
    environment:
      - API_BASE_URL=http://back:8000
      - DEBUG=False
    depends_on:
      - back
    volumes:
    - ./front/src:/app/src
    - ./front/data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uv-cache: