
services:
  db:
    image: postgres:13
    container_name: accident_severity_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accidents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d accidents"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: accident_severity_back
    #image: ghcr.io/inesmarouani/accident-back:develop  # ← Image GHCR
    ports:
      - "8000:8000"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: accidents
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./back/models_trained:/code/models_trained
      # Volume pour uv cache (optionnel, améliore les rebuild)
      - uv-cache:/root/.cache/uv
    networks:
      - app-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: accident_severity_front
    image: ghcr.io/inesmarouani/accident-front:develop  # ← Image GHCR
    ports:
      - "8050:8050"
    environment:
      - API_BASE_URL=http://back:8000
      - DEBUG=False
    depends_on:
      - back
    volumes:
    - ./front/src:/app/src
    - ./front/data:/app/data
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml # Ajout de alert.rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    volumes:
      - grafana-data:/var/lib/grafana
      - ./fastapi-dashboard.json:/etc/grafana/provisioning/dashboards/fastapi-dashboard.json
      - ./provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - app-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  postgres_data:
  uv-cache:
  grafana-data:
  prometheus_data:
